Repository cubicon-feup/mygrant, pull requests merged in 2018-05, with the labels that each got.

#47 Feature/comments
  client/src/components/Comments.js
  client/src/components/Service.js
  client/src/scss/Comments.scss
  client/src/scss/Service.scss
Labels: frontend

#53 Comments Frontend
  client/src/components/Comments.js
  client/src/components/CreateService.js
  client/src/components/Service.js
  client/src/components/ServiceOffers.js
  client/src/scss/Comments.scss
Labels: frontend

#50 Services use cookies
  client/src/components/CreateService.js
  client/src/components/ImgGrid.js
  client/src/components/Service.js
  client/src/components/ServiceOffers.js
  routes/services.js
  routes/users.js
Labels: frontend

#54 Feature/crowdfunding
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  app.js
  client/public/img/mission.png
  client/public/img/user.jpg
  client/src/Role.js
  client/src/components/Comments.js
  client/src/components/CreateCrowdfunding.js
  client/src/components/CreateServiceCrowdfunding.js
  client/src/components/Crowdfunding.js
  client/src/components/Crowdfundings.js
  client/src/components/Donator.js
  client/src/components/SearchCrowdfunding.js
  client/src/components/Service.js
  client/src/components/comments/CommentStandard.js
  client/src/components/comments/Comments.js
  client/src/components/service_offers/CrowdfundingOffers.js
  client/src/components/service_offers/RequestedServiceItem.js
  client/src/components/service_offers/SelectedRequester.js
  client/src/config.js
  client/src/containers/Dashboard.js
  client/src/containers/SearchPage.js
  client/src/index.js
  client/src/scss/Comments.scss
  client/src/scss/Crowdfunding.scss
  client/src/scss/Search.scss
  cronjob.js
  package.json
  routes/comments.js
  routes/crowdfundings.js
  routes/images.js
  routes/messages.js
  routes/services.js
  routes/users.js
Labels: backend, frontend

#55 Fix packages
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
Labels: bug

#58 Feature/microblogging
  app.js
  client/src/components/BlogComment.js
  client/src/components/BlogHeader.js
  client/src/components/BlogHeaderPost.js
  client/src/components/BlogPost.js
  client/src/components/MygrantHeader.js
  client/src/components/NewPost.js
  client/src/containers/Blog.js
  client/src/containers/Conversation.js
  client/src/containers/Feed.js
  client/src/containers/Post.js
  client/src/index.js
  client/src/scss/Blog.scss
  client/src/scss/common.scss
  migrations/4-5.sql
  routes/posts.js
  routes/users.js
Labels: backend, frontend

#56 PigeonMaps & Nominatim
  client/package-lock.json
  client/package.json
  client/src/components/CreateCrowdfunding.js
  client/src/components/CreateService.js
  client/src/components/Crowdfunding.js
  client/src/components/Map.js
  client/src/components/SearchLocation.js
  client/src/components/Service.js
  client/src/containers/Signup.js
  client/src/containers/SignupInfo.js
  client/src/index.js
  client/src/scss/common.scss
  routes/auth.js
  routes/users.js
Labels: frontend

#51 Profile almost done (missing edit)
  app.js
  client/package-lock.json
  client/src/components/User.js
  client/src/scss/User.scss
  client/src/scss/common.scss
  package-lock.json
  routes/users.js
Labels: backend, frontend

#57 Search
  client/src/components/Donator.js
  client/src/components/ListCrowdfunding.js
  client/src/components/ListService.js
  client/src/components/MygrantHeader.js
  client/src/components/SearchCrowdfunding.js
  client/src/components/SearchService.js
  client/src/components/service_offers/RequestedServiceItem.js
  routes/crowdfundings.js
  routes/services.js
Labels: frontend

#60 Added api to allow change to user image
  images/Image.js
  routes/users.js
Labels: backend
