Repository cubicon-feup/mygrant, pull requests merged in 2018-04, with the labels that each got.

#6 Add support for nodemon via 'npm run dev'
  package.json
Labels: enhancement

#9 Basic structure to create a Service
  client/src/components/CreateService.js
  client/src/index.js
Labels: frontend

#8 added tests to appInfo route and some mocking tests
  .babelrc
  .gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/components/App.js
  client/src/tests/CheckboxWithLabel.js
  client/src/tests/CheckboxWithLabel.test.js
  client/test/App.test.js
  package-lock.json
  package.json
  tests/appInfo.test.js
  tests/mockTest/__mocks__/user.js
  tests/mockTest/user.js
  tests/user.test.js
  tests/userMock.test.js
Labels: tests

#14 Check if input is valid & display
  client/src/components/CreateService.js
Labels: frontend

#24 get User by id & User page
  client/src/components/User.js
  client/src/index.js
  package-lock.json
  routes/users.js
Labels: backend, frontend

#25 Lots of stuff about Services
  app.js
  client/src/components/CreateService.js
  client/src/components/Service.js
  client/src/components/ServiceOffers.js
  client/src/components/TableServices.js
  client/src/index.js
  client/src/scss/App.scss
  package-lock.json
  routes/services.js
  routes/users.js
Labels: frontend
